import { Exercise, WorkoutLocation } from './types';

export const EXERCISES: Exercise[] = [
  // --- BACK ---
  { id: 'back_1', name: 'Lat Pulldown', muscles: ['Back'], sets: 3, reps: '10–12', instruction: 'Pull the bar to your upper chest.', image: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Lat Pulldown' },
  { id: 'back_1_rep', name: 'Assisted Pull-ups (Band)', muscles: ['Back', 'Arms'], sets: 3, reps: '8–10', instruction: 'Use resistance band to assist pull-ups, focus on controlled movement.', image: 'Screenshot 2025-12-30 at 12.03.25 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', isReplacement: true, replacesId: 'back_1' },
  { id: 'back_2', name: 'Seated Cable Row', muscles: ['Back'], sets: 3, reps: '10–12', instruction: 'Pull handle to waist, keep back straight.', image: 'https://images.unsplash.com/photo-1590239068512-632739f9ea48?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Rower' },
  { id: 'back_2_rep', name: 'Resistance Band Row', muscles: ['Back'], sets: 3, reps: '12–15', instruction: 'Anchor band at chest height and row back, squeeze shoulder blades.', image: 'Screenshot 2025-12-30 at 12.01.58 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', isReplacement: true, replacesId: 'back_2' },
  { id: 'back_3', name: 'Barbell Row', muscles: ['Back'], sets: 3, reps: '8–10', instruction: 'Bend forward, pull bar to ribs.', image: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Barbells' },
  { id: 'back_4', name: 'Deadlift', muscles: ['Back', 'Legs'], sets: 3, reps: '5–8', instruction: 'Lift from ground to hips.', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Barbells' },
  { id: 'back_5', name: 'Pull Ups', muscles: ['Back', 'Arms'], sets: 3, reps: 'Max', instruction: 'Chin over bar, control descent.', image: 'Screenshot 2025-12-30 at 12.00.24 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Intermediate' },
  { id: 'back_6', name: 'T-Bar Row', muscles: ['Back'], sets: 3, reps: '10–12', instruction: 'Pull weight to torso.', image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Barbells' },

  // --- BICEPS ---
  { id: 'bicep_1', name: 'Barbell Bicep Curl', muscles: ['Biceps'], sets: 3, reps: '10–12', instruction: 'Curl bar to shoulders.', image: 'Screenshot 2025-12-29 at 8.23.37 PM.png', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Barbells' },
  { id: 'bicep_2', name: 'Dumbbell Bicep Curl', muscles: ['Biceps'], sets: 3, reps: '12', instruction: 'Rotate palms up as you curl.', image: 'Screenshot 2025-12-29 at 8.11.47 PM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', equipmentRequired: 'Dumbbells' },
  { id: 'bicep_3', name: 'Hammer Curl', muscles: ['Biceps'], sets: 3, reps: '12', instruction: 'Palms face inward.', image: 'Screenshot 2025-12-29 at 8.19.00 PM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', equipmentRequired: 'Dumbbells' },
  { id: 'bicep_4', name: 'Preacher Curl (Machine)', muscles: ['Biceps'], sets: 3, reps: '10', instruction: 'Arms on pad, curl up.', image: 'https://gymstogo.com/wp-content/uploads/2020/12/MSEC_01-600x600.jpg', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Seated Curl' },
  { id: 'bicep_5', name: 'Concentration Curl', muscles: ['Biceps'], sets: 3, reps: '12', instruction: 'Isolate bicep against leg.', image: 'Screenshot 2025-12-29 at 11.49.20 PM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', equipmentRequired: 'Dumbbells' },

  // --- CHEST ---
  { id: 'chest_1', name: 'Bench Press', muscles: ['Chest'], sets: 3, reps: '8–10', instruction: 'Press bar vertically.', image: 'Screenshot 2025-12-30 at 3.40.47 PM.png', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Barbells' },
  { id: 'chest_1_rep', name: 'Push-ups', muscles: ['Chest'], sets: 3, reps: '15+', instruction: 'Standard push-ups with proper form, keep body straight.', image: 'Screenshot 2025-12-30 at 12.23.18 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', isReplacement: true, replacesId: 'chest_1' },
  { id: 'chest_2', name: 'Incline Dumbbell Press', muscles: ['Chest', 'Shoulders'], sets: 3, reps: '10', instruction: 'Targets upper chest.', image: 'Screenshot 2025-12-30 at 12.19.06 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Intermediate', equipmentRequired: 'Dumbbells' },
  { id: 'chest_3', name: 'Chest Fly (Machine)', muscles: ['Chest'], sets: 3, reps: '12', instruction: 'Squeeze handles together.', image: 'Screenshot 2025-12-30 at 3.42.33 PM.png', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Chest Fly' },
  { id: 'chest_3_rep', name: 'Resistance Band Fly', muscles: ['Chest'], sets: 3, reps: '15', instruction: 'Anchor bands behind you and fly arms forward, squeeze chest.', image: 'Screenshot 2025-12-30 at 12.24.50 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', isReplacement: true, replacesId: 'chest_3' },
  { id: 'chest_4', name: 'Push Ups', muscles: ['Chest'], sets: 3, reps: '15+', instruction: 'Keep body straight.', image: 'https://www.realsimple.com/thmb/-PW_i-RMLQ4cj3-okjqccGGUock%3D/1500x0/filters%3Ano_upscale%28%29%3Amax_bytes%28150000%29%3Astrip_icc%28%29/health-benefits-of-pushups-GettyImages-498315681-7008d40842444270868c88b516496884.jpg', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner' },
  { id: 'chest_5', name: 'Cable Crossover', muscles: ['Chest'], sets: 3, reps: '12', instruction: 'Constant tension on chest.', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Cable Machine' },

  // --- SHOULDERS ---
  { id: 'shoulder_1', name: 'Shoulder Press', muscles: ['Shoulders'], sets: 3, reps: '10', instruction: 'Press dumbbells up.', image: 'Screenshot 2025-12-30 at 12.29.58 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', equipmentRequired: 'Dumbbells' },
  { id: 'shoulder_2', name: 'Lateral Raise', muscles: ['Shoulders'], sets: 3, reps: '15', instruction: 'Raise arms out to sides.', image: 'Screenshot 2025-12-30 at 12.36.26 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', equipmentRequired: 'Dumbbells' },
  { id: 'shoulder_3', name: 'Front Raise', muscles: ['Shoulders'], sets: 3, reps: '12', instruction: 'Raise dumbbells in front.', image: 'Screenshot 2025-12-29 at 11.42.31 PM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', equipmentRequired: 'Dumbbells' },
  { id: 'shoulder_4', name: 'Rear Delt Fly', muscles: ['Shoulders'], sets: 3, reps: '15', instruction: 'Lean forward, fly back.', image: 'https://images.unsplash.com/photo-1590487949433-a421d590650a?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Chest Fly' },
  { id: 'shoulder_5', name: 'Arnold Press', muscles: ['Shoulders'], sets: 3, reps: '10', instruction: 'Rotate palms as you press.', image: 'Screenshot 2025-12-30 at 12.38.05 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Intermediate', equipmentRequired: 'Dumbbells' },

  // --- LEGS ---
  { id: 'leg_1', name: 'Squats', muscles: ['Legs'], sets: 3, reps: '12', instruction: 'Keep heels flat.', image: 'Screenshot 2025-12-30 at 12.17.31 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner' },
  { id: 'leg_2', name: 'Leg Press', muscles: ['Legs'], sets: 3, reps: '12', instruction: 'Press away with heels.', image: 'https://hips.hearstapps.com/hmg-prod/images/woman-lifting-weight-on-legs-royalty-free-image-1704915259.jpg', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Leg Press' },
  { id: 'leg_2_rep', name: 'Goblet Squats', muscles: ['Legs'], sets: 3, reps: '12', instruction: 'Hold weight close to chest, squat down keeping weight balanced.', image: 'Screenshot 2025-12-30 at 12.16.05 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', isReplacement: true, replacesId: 'leg_2' },
  { id: 'leg_3', name: 'Leg Extension', muscles: ['Legs'], sets: 3, reps: '15', instruction: 'Isolates quads.', image: 'Screenshot 2025-12-30 at 3.45.48 PM.png', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Leg Extension' },
  { id: 'leg_3_rep', name: 'Bodyweight Leg Extensions', muscles: ['Legs'], sets: 3, reps: '20', instruction: 'Sit on edge of bench, extend legs forward, hold and squeeze quads.', image: 'Screenshot 2025-12-30 at 12.13.55 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', isReplacement: true, replacesId: 'leg_3' },
  { id: 'leg_4', name: 'Leg Curl', muscles: ['Legs'], sets: 3, reps: '15', instruction: 'Isolates hamstrings.', image: 'https://images.unsplash.com/photo-1590487949433-a421d590650a?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Leg Curl' },
  { id: 'leg_4_rep', name: 'Hamstring Curls (Resistance Band)', muscles: ['Legs'], sets: 3, reps: '15', instruction: 'Anchor band behind you, curl heel toward glutes.', image: 'Screenshot 2025-12-30 at 12.09.18 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', isReplacement: true, replacesId: 'leg_4' },
  { id: 'leg_5', name: 'Calf Raises', muscles: ['Legs'], sets: 3, reps: '20', instruction: 'Stand on toes.', image: 'Screenshot 2025-12-30 at 12.10.48 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner' },

  // --- TRICEPS ---
  { id: 'tricep_1', name: 'Tricep Pushdown (Cable)', muscles: ['Triceps'], sets: 3, reps: '12', instruction: 'Push bar down.', image: 'https://images.unsplash.com/photo-1598971639058-aba7c12af674?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Cable Machine' },
  { id: 'tricep_2', name: 'Skull Crushers', muscles: ['Triceps'], sets: 3, reps: '10', instruction: 'Bar to forehead, extend up.', image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Barbells' },
  { id: 'tricep_3', name: 'Overhead Extension', muscles: ['Triceps'], sets: 3, reps: '12', instruction: 'Extend weight overhead.', image: 'Screenshot 2025-12-30 at 12.39.46 AM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Beginner', equipmentRequired: 'Dumbbells' },
  { id: 'tricep_4', name: 'Dips', muscles: ['Triceps'], sets: 3, reps: 'Max', instruction: 'Lower between bars.', image: 'screenshot 2025-12-29 at 11.34.14 PM.png', category: 'Strength', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Intermediate' },
  { id: 'tricep_5', name: 'Close Grip Bench', muscles: ['Triceps'], sets: 3, reps: '10', instruction: 'Narrow hand position.', image: 'https://images.unsplash.com/photo-1534367958379-246df1629853?q=80&w=1000', category: 'Strength', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Barbells' },

  // --- GYM CORE/ABS ---
  { id: 'ab_g1', name: 'Ab Crunch Machine', muscles: ['Core'], sets: 3, reps: '15', instruction: 'Sit in the machine and crunch your torso down against the resistance.', image: 'https://gymstogo.com/wp-content/uploads/2020/12/MSEC_01-600x600.jpg', category: 'Core', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Ab Crunch Machine' },
  { id: 'ab_g2', name: 'Hanging Leg Raise', muscles: ['Core'], sets: 3, reps: '10–12', instruction: 'Hang from a bar and lift your legs up to parallel or higher without swinging.', image: 'https://images.unsplash.com/photo-1598971639058-aba7c12af674?q=80&w=1000', category: 'Core', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Pull Up Bar' },
  { id: 'ab_g3', name: 'Cable Crunch', muscles: ['Core'], sets: 3, reps: '15', instruction: 'Kneel in front of a cable station, hold rope behind head, and crunch down.', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000', category: 'Core', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Cable Machine' },
  { id: 'ab_g4', name: 'Decline Sit-Ups', muscles: ['Core'], sets: 3, reps: '15', instruction: 'Perform sit-ups on a decline bench for added intensity.', image: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?q=80&w=1000', category: 'Core', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Decline Bench' },
  { id: 'ab_g5', name: 'Ab Roller / Ab Wheel', muscles: ['Core'], sets: 3, reps: '10', instruction: 'Roll out as far as you can with good form and pull back in using your abs.', image: 'https://cdn.mos.cms.futurecdn.net/v2/t%3A0%2Cl%3A1317%2Ccw%3A3386%2Cch%3A3386%2Cq%3A80%2Cw%3A2560/Hu2Hogef5PxR6gkRXpPDBc.jpg', category: 'Core', location: [WorkoutLocation.GYM, WorkoutLocation.HOME], difficulty: 'Intermediate', equipmentRequired: 'Ab Roller' },
  { id: 'ab_g6', name: 'Captain’s Chair Leg Raise', muscles: ['Core'], sets: 3, reps: '12', instruction: 'Use the captain\'s chair to support your back and lift knees to chest.', image: 'https://www.gymsolutions.com.au/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-07-at-17.39.28_98c77776.jpg', category: 'Core', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Captain’s Chair' },

  // --- HOME CORE/ABS ---
  { id: 'ab_h1', name: 'Plank', muscles: ['Core'], sets: 3, reps: '60s', instruction: 'Hold a straight line from head to heels on your forearms.', image: 'https://hips.hearstapps.com/hmg-prod/images/transverse-abdonimis-trevor-raab-fitness-shoots-0293-1646247932.jpg', category: 'Core', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' },
  { id: 'ab_h2', name: 'Crunches', muscles: ['Core'], sets: 3, reps: '20', instruction: 'Lie on your back and curl your shoulders towards your hips.', image: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2025-04/mountain-climbers-cardio-exercise-te-250415-b119db.gif', category: 'Core', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' },
  { id: 'ab_h3', name: 'Leg Raises', muscles: ['Core'], sets: 3, reps: '15', instruction: 'Lie flat and lift your legs to 90 degrees, then lower them slowly.', image: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2025-04/mountain-climbers-cardio-exercise-te-250415-b119db.gif', category: 'Core', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' },
  { id: 'ab_h4', name: 'Bicycle Crunch', muscles: ['Core'], sets: 3, reps: '20', instruction: 'Bring opposite elbow to opposite knee in a cycling motion.', image: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2025-04/mountain-climbers-cardio-exercise-te-250415-b119db.gif', category: 'Core', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Intermediate' },
  { id: 'ab_h5', name: 'Mountain Climbers', muscles: ['Core', 'Heart'], sets: 3, reps: '45s', instruction: 'Drive your knees to your chest from a plank position.', image: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2025-04/mountain-climbers-cardio-exercise-te-250415-b119db.gif', category: 'Core', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' },
  { id: 'ab_h6', name: 'Russian Twist', muscles: ['Core'], sets: 3, reps: '20', instruction: 'Sit with knees bent, feet off floor, and rotate torso side to side.', image: 'https://hips.hearstapps.com/hmg-prod/images/portrait-of-barechested-muscular-man-practicing-royalty-free-image-1663776097.jpg', category: 'Core', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Intermediate' },

  // --- GYM CARDIO ---
  { id: 'gc_1', name: 'Treadmill', muscles: ['Heart', 'Legs'], sets: 1, reps: '20 mins', instruction: 'Walking / Running.', image: 'https://static.nike.com/a/images/f_auto,cs_srgb/w_1536,c_limit/6a2dbeb8-e877-42c1-ae92-52e1ae29799f/3-treadmill-workouts-that-can-boost-your-fitness.jpg', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Treadmill' },
  { id: 'gc_2', name: 'Elliptical Trainer', muscles: ['Heart', 'Legs'], sets: 1, reps: '15 mins', instruction: 'Low impact cardio.', image: 'https://www.verywellfit.com/thmb/IKFDapYoWte6fznWC8nF_kf2l2Q%3D/1500x0/filters%3Ano_upscale%28%29%3Amax_bytes%28150000%29%3Astrip_icc%28%29/1230802-GettyImages-1391115901-bb3ca635045e489a93bdeacbc016ff1b.jpg', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Elliptical' },
  { id: 'gc_3', name: 'Rowing Machine', muscles: ['Heart', 'Full Body'], sets: 1, reps: '10 mins', instruction: 'Pull handle to chest.', image: 'https://res.cloudinary.com/hydrow/image/upload/f_auto/w_3840/q_100/v1717007026/muscles-worked-rowing-the-recovery.png', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Rower' },
  { id: 'gc_4', name: 'Stationary Bike (Upright)', muscles: ['Heart', 'Legs'], sets: 1, reps: '20 mins', instruction: 'Standard cycling.', image: 'https://hips.hearstapps.com/hmg-prod/images/wahoo-fitness-kickr-bike-v2-678680ddf0090.jpg', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Upright Bike' },
  { id: 'gc_5', name: 'Stationary Bike (Recumbent)', muscles: ['Heart', 'Legs'], sets: 1, reps: '20 mins', instruction: 'Seated cycling.', image: 'Screenshot 2025-12-29 at 8.29.21 PM.png', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Beginner', equipmentRequired: 'Recumbent Bike' },
  { id: 'gc_6', name: 'Spin Bike', muscles: ['Heart', 'Legs'], sets: 1, reps: '15 mins', instruction: 'High intensity cycling.', image: 'https://hips.hearstapps.com/hmg-prod/images/wahoo-fitness-kickr-bike-v2-678680ddf0090.jpg', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Spin Bike' },
  { id: 'gc_7', name: 'Stair Climber', muscles: ['Heart', 'Legs'], sets: 1, reps: '10 mins', instruction: 'Climb at steady pace.', image: 'https://echelonfit.com/cdn/shop/files/StairClimberSport_MAIN_Image.jpg', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Stair Climber' },
  { id: 'gc_8', name: 'Air Bike', muscles: ['Heart', 'Full Body'], sets: 1, reps: '5 mins', instruction: 'Push/pull handles.', image: 'https://images.ctfassets.net/8urtyqugdt2l/55RwL0ulr5XFA96XpzTHOJ/3b789fae6253c3c4e88d84291200d0ec/desktop-assault-bike-workouts.jpg', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Air Bike' },
  { id: 'gc_9', name: 'Ski Ergometer', muscles: ['Heart', 'Arms', 'Back'], sets: 1, reps: '5 mins', instruction: 'Mimic skiing motion.', image: 'https://repfitness.com/cdn/shop/products/20170718_bharrewyn_concept2ski_sequence-16.jpg', category: 'Cardio', location: [WorkoutLocation.GYM], difficulty: 'Intermediate', equipmentRequired: 'Ski Erg' },

  // --- HOME CARDIO ---
  { id: 'hc_1', name: 'Jumping Jacks', muscles: ['Heart', 'Full Body'], sets: 3, reps: '1 min', instruction: 'Jump and spread arms/legs.', image: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2025-04/mountain-climbers-cardio-exercise-te-250415-b119db.gif', category: 'Cardio', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' },
  { id: 'hc_2', name: 'High Knees', muscles: ['Heart', 'Legs'], sets: 3, reps: '45 secs', instruction: 'Run in place, knees high.', image: 'https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1240w,f_auto,q_auto:best/rockcms/2025-04/mountain-climbers-cardio-exercise-te-250415-b119db.gif', category: 'Cardio', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' },
  { id: 'hc_4', name: 'Burpees', muscles: ['Heart', 'Full Body'], sets: 3, reps: '10', instruction: 'Squat, kick back, push up, jump.', image: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?q=80&w=1000', category: 'Cardio', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Intermediate' },
  { id: 'hc_5', name: 'Running in Place', muscles: ['Heart', 'Legs'], sets: 3, reps: '2 mins', instruction: 'Steady pace jogging.', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000', category: 'Cardio', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' },
  { id: 'hc_6', name: 'Skipping (Rope)', muscles: ['Heart', 'Legs'], sets: 3, reps: '1 min', instruction: 'Standard rope jumping.', image: 'https://images.unsplash.com/photo-1598971639058-aba7c12af674?q=80&w=1000', category: 'Cardio', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' },
  { id: 'hc_7', name: 'Shadow Boxing', muscles: ['Heart', 'Arms'], sets: 3, reps: '2 mins', instruction: 'Mimic boxing in air.', image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000', category: 'Cardio', location: [WorkoutLocation.HOME, WorkoutLocation.GYM], difficulty: 'Beginner' }
];

export const GYM_EQUIPMENT_LIST = [
  { id: 'Treadmill', name: 'Treadmill', icon: '🏃', image: 'https://static.nike.com/a/images/f_auto,cs_srgb/w_1536,c_limit/6a2dbeb8-e877-42c1-ae92-52e1ae29799f/3-treadmill-workouts-that-can-boost-your-fitness.jpg' },
  { id: 'Elliptical', name: 'Elliptical Trainer', icon: '🚲', image: 'https://www.verywellfit.com/thmb/IKFDapYoWte6fznWC8nF_kf2l2Q%3D/1500x0/filters%3Ano_upscale%28%29%3Amax_bytes%28150000%29%3Astrip_icc%28%29/1230802-GettyImages-1391115901-bb3ca635045e489a93bdeacbc016ff1b.jpg' },
  { id: 'Rower', name: 'Rowing Machine', icon: '🚣', image: 'https://res.cloudinary.com/hydrow/image/upload/f_auto/w_3840/q_100/v1717007026/muscles-worked-rowing-the-recovery.png' },
  { id: 'Upright Bike', name: 'Upright Bike', icon: '🚴', image: 'https://hips.hearstapps.com/hmg-prod/images/wahoo-fitness-kickr-bike-v2-678680ddf0090.jpg' },
  { id: 'Recumbent Bike', name: 'Recumbent Bike', icon: '🪑', image: 'https://www.gymsolutions.com.au/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-07-at-17.39.28_98c77776.jpg' },
  { id: 'Spin Bike', name: 'Spin Bike', icon: '🔥', image: 'https://hips.hearstapps.com/hmg-prod/images/wahoo-fitness-kickr-bike-v2-678680ddf0090.jpg' },
  { id: 'Stair Climber', name: 'Stair Climber', icon: '🪜', image: 'https://echelonfit.com/cdn/shop/files/StairClimberSport_MAIN_Image.jpg' },
  { id: 'Air Bike', name: 'Air Bike', icon: '💨', image: 'https://images.ctfassets.net/8urtyqugdt2l/55RwL0ulr5XFA96XpzTHOJ/3b789fae6253c3c4e88d84291200d0ec/desktop-assault-bike-workouts.jpg' },
  { id: 'Ski Erg', name: 'Ski Ergometer', icon: '🎿', image: 'https://repfitness.com/cdn/shop/products/20170718_bharrewyn_concept2ski_sequence-16.jpg' },
  { id: 'Leg Press', name: 'Leg Press', icon: '🦵', image: 'https://hips.hearstapps.com/hmg-prod/images/woman-lifting-weight-on-legs-royalty-free-image-1704915259.jpg' },
  { id: 'Lat Pulldown', name: 'Lat Pulldown', icon: '👐', image: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?q=80&w=1000' },
  { id: 'Chest Fly', name: 'Chest Fly', icon: '🦋', image: 'https://www.gymsolutions.com.au/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-07-at-17.39.28_98c77776.jpg' },
  { id: 'Seated Curl', name: 'Curl Machine', icon: '💪', image: 'https://gymstogo.com/wp-content/uploads/2020/12/MSEC_01-600x600.jpg' },
  { id: 'Barbells', name: 'Barbells', icon: '🏋️', image: 'https://m.media-amazon.com/images/I/61z1KayVDBL.jpg' },
  { id: 'Dumbbells', name: 'Dumbbells', icon: '⚖️', image: 'https://www.gymsolutions.com.au/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-07-at-17.39.28_98c77776.jpg' },
  { id: 'Cable Machine', name: 'Cable Machine', icon: '⛓️', image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1000' },
  { id: 'Leg Extension', name: 'Leg Extension', icon: '🦵', image: 'https://images.unsplash.com/photo-1591940746262-b2f4f7fa0a8a?q=80&w=1000' },
  { id: 'Leg Curl', name: 'Leg Curl', icon: '➰', image: 'https://images.unsplash.com/photo-1590487949433-a421d590650a?q=80&w=1000' },
  { id: 'Ab Crunch Machine', name: 'Ab Crunch Machine', icon: '📉', image: 'https://gymstogo.com/wp-content/uploads/2020/12/MSEC_01-600x600.jpg' },
  { id: 'Pull Up Bar', name: 'Pull Up Bar / Power Tower', icon: '🏗️', image: 'https://images.unsplash.com/photo-1598971639058-aba7c12af674?q=80&w=1000' },
  { id: 'Decline Bench', name: 'Decline Bench', icon: '🪑', image: 'https://images.unsplash.com/photo-1544033527-b192daee1f5b?q=80&w=1000' },
  { id: 'Ab Roller', name: 'Ab Roller Wheel', icon: '🛞', image: 'https://cdn.mos.cms.futurecdn.net/v2/t%3A0%2Cl%3A1317%2Ccw%3A3386%2Cch%3A3386%2Cq%3A80%2Cw%3A2560/Hu2Hogef5PxR6gkRXpPDBc.jpg' },
  { id: 'Captain’s Chair', name: 'Captain’s Chair', icon: '💺', image: 'https://www.gymsolutions.com.au/wp-content/uploads/2024/11/WhatsApp-Image-2024-11-07-at-17.39.28_98c77776.jpg' }
];